### ISSUE TITLE
Crash when launching minecraft

### ISSUE THREAD

**Issue by NewMilenium** [hm-ysjiang/PotionCapsule#1]
I simply launched Minecraft 1.14.4 with forge and a few mods including yours; it was working fine without your mod, it crashes with it. 

**Information :**
 - Mod Version: the only available one
 - Forge Version: 1.14.4-forge-28.0.49
 - Crash Log: https://pastebin.com/Ya1Yupfb

Don't hesitate to ask me if i can provide more information.

**Comment by OCDCleric** [comment]
I got the same issue.

**Comment by hm-ysjiang** [comment]
My fault, still using the old transformer

Should be fixed in [1.0.3](https://www.curseforge.com/minecraft/mc-mods/potion-capsule/files/2777481)
