### ISSUE TITLE
edited : The file "potioncapsule-server.toml" in "config" is misleading

### ISSUE THREAD

**Issue by NewMilenium** [hm-ysjiang/PotionCapsule#3]
In "potioncapsule-server.toml" (and i checked, there is not this option in "potioncapsule-client.toml" ) :

>  [recipe]
> 	\# Set this to true will enable the crafting recipe of Nether Wart Dust
> 	enableWartDust = true

and yet i can't craft WartDust. JEI doesn't find any recipe to craft Wart Dust, putting a nether wart anywhere in a crafting bench or in a crafting station doesn't have any visible result, and clicking the "result" case doesn't do anything neither.

I still manage to find some scarce Wart Dust when destroying mature Nether Warts.

**Information :**
- Mod Version: PotionCapsule-1.0.3
- Forge Version: 1.14.4-forge-28.0.49
- Crash Log: no crash

**Additional context**
Mods used : 
branders-enhanced-mob-spawners.v1.4.2-1.14.4,
buildinggadgets-3.0.4,
ChunkNoGoByeBye-1.14.4-1.0.2,
craftingstation-2.0.2a,
curios-FORGE-1.14.4-0.23,
EnderBags-1.14.4-4.1.2,
exp_bottling-1.14.4-3,
ForgivingVoid_1.14.2-3.0.5,
gates-1.2.0 <-- not functional anymore, not working since the moment i put your mod,
gravestone-1.15.0,
jei-1.14.4-6.0.0.10,
Mine+and+Slash-1.14.4-2.5.2,
Placebo-1.14.4-2.1.11,
PotionCapsule-1.0.3,
spiketraps-1.0,
Xaeros_Minimap_1.17.6_Forge_1.14.4

**Comment by hm-ysjiang** [comment]
Which server config are you changing? The one in the config folder or the one in the serverconfig inside your world save?

EDIT: 
I have tested this problem, it works fine. I think you might have changed the wrong config file.
It seems like the actual server config file the game is reading is not the one in the old config folder but in a folder named serverconfig inside each world save.

I am not sure if it is my problem that the game is generating a server config in the old config folder, I will take a look at it, hope to find some solution.

**Comment by NewMilenium** [comment]
Good job, you're perfectly right (just tested).
So, the issue is not the one i've written, but instead : "_two files in the config folder are misleading, as they're not taken in count, the one we have to modify is the one in '**serverconfig**' in the world save_".

**Comment by hm-ysjiang** [comment]
Yep, the client config is in the config folder, and the server one is in serverconfig inside each world save.

**Comment by hm-ysjiang** [comment]
Closing this since there is not much I can do right now
