### ISSUE TITLE
conflicting loot table methods

### ISSUE THREAD

**Issue by IchigoGames** [hm-ysjiang/PotionCapsule#7]
This is a bug report to multiple others invoicing multiple mods i'm going to write this in a way that makes it possible to
copy and paste as much of this as i can into each mod others issue page sorry if this is not in the right format.

The issue i am having is that all most all loot chests in my world are empty this is a new world btw after a lot of testing
removing and adding mods one at a time iv come up with a list of mods that by them selfs may work find but when put into 
a modpack are conflicting  with each other and the result is a empty loot chests the mods will be listed below

Jack-O'-Launcher-1.14.4-1.2.0
mysticalworld-1.14.4-1.5.1
PotionCapsule-1.1.0

all i ask is that each of you look at how your adding your items into the loot table and make sure its the correct method
and not done in a way that would easily confetti with other mods trying to add there items into the same chests.

if anyone of you need more info please let me know and thank you for your time.

**Comment by IchigoGames** [comment]
the listed mods aslo conflict with mod like EnigmaticLegacy-1.4.0 Apotheosis-1.14.4-2.4.1 and SilentGems-1.14.4-3.4.6+79 but with just these mods and not the mods in the issue report they all work together and the chest are not empty.

**Comment by hm-ysjiang** [comment]
Okay, should be fixed in the next build
